### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by deionalims** [eyal-lezmy/android-things-workshop#5]
Hello guys,

Thank you for this nice workshop. It's really helpful.
I started to play around with AndroidThings myself. 
Here is a little project I did. Any comment is more than welcome.
https://github.com/deionalims/NextTrain-AndroidThings

I would like to know more about the `close()` method we should call on any device used.
What does it do exactly ? 
What is the right pattern related to this ? Should we close it as quick as possible ? Or should we let the device "open" if we know that we will eventually update it ? 
What happens if we don't `close()` it ? 

Thanks \o/

**Comment by eyal-lezmy** [comment]
Hi @deionalims,

Thanks for the feedback 😃 

The `close` method is used to release the pins your application is connected to. To let another application using it. 
The most common pattern is to close them when `onDestroy` is called.

One important point here is that Android Things is an OS where all the application layer is aimed to be controlled by the manufacturer (the creator of the device). This means that no other application than yours will access those pins. `close` method is a simple way to make the switch between different applications that needs to access the same pin, but I don't think this switch should be a common use case.

If you don't call `close` on a pin and another application try to open it, the runtime will throw an exception telling `DEVICE_NAME is already in use`. A reboot will release all the pins of course.

Considering we don't really know how much it will be easy or feasible to connect and manage several applications on your devices (through the IOT dev console) I would recommend to follow the common pattern which is closing on `onDestroy`.

I hope this helped
Cheers

**Comment by deionalims** [comment]
It did.

Thank you very much. 👍

**Comment by eyal-lezmy** [comment]
Ok so let me close this issue. Cheers ;-)
